name: "Deploy para a VPS"

on:
  push:
    branches:
      - main

jobs: 
  build_deploy:
    runs-on: ubuntu-latest

    steps: 
      - name: "📤 Baixar o código"
        uses: actions/checkout@v4

      - name: "📤 Copiar arquivos para a VPS"
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzv0 --exclude='.env'"
          SOURCE: "."
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.API_READOVER_TARGET }}
      - name: "🐳 Recarregar containers Docker"
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 
          script: |
            cd ${{ secrets.API_READOVER_TARGET }}
            docker compose down
            docker compose up -d --build
